accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

articles/urls.py
from django.urls import path
from .views import (
    article_list_view,
    article_detail_view,
    article_search_view,
    article_create_view,
    article_update_view,
    article_delete_view,
)

app_name = 'articles'

urlpatterns = [
    path('', article_list_view, name='article_list'),
    path('detail/<slug:slug>/', article_detail_view, name='article_detail'),
    path('search/', article_search_view, name='article_search'),
    path('create/', article_create_view, name='article_create'),
    path('edit/<int:pk>/', article_update_view, name='article_update'),
    path('delete/<int:pk>/', article_delete_view, name='article_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('recipe/', include('recipes.urls', namespace='recipes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



def _login_view(request):
    query_dict = request.POST
    username = query_dict.get('username')
    password = query_dict.get('password')
    if request.method == 'POST':
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {"error": "bunday foydalanuvchi mavjud emas"}
            return render(request, 'accounts/login.html', context)
        login(request, user)
        return redirect('/')

    return render(request, 'accounts/login.html')


def login_view(request):
    form = AuthenticationForm(request)
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)



@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')
    return render(request, 'accounts/logout.html')


def signup_view(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    {% if not error  %}
        <form method="post">
        {% csrf_token %}
        <div>
{#            <input type="text" name="username" placeholder="username">#}
            {{ form.username }}
        </div>
        <br>
        <div>
{#            <input type="password" name="password" placeholder="password" >#}
            {{ form.password }}
        </div>
        <br>
        <button type="submit">Login</button>
        <p>Manda akkountim yoq, <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
    </form>

        {% else %}
        <p>Bunday user topilmadi, <a href="{% url 'accounts:login' %}">Boshqadan harakat qilib koring</a></p>
    {% endif %}


{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}

    <h4>Rostanham chiqib ketmoqchimsiiz</h4>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Log out</button>
        <a href="{% url 'articles:article_list' %}">Orqaga</a>
    </form>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}


{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Signup</button>
        <p>Menda akkountim bor, <a href="{% url 'accounts:login' %}">Login</a></p>
    </form>

{% endblock %}