articles/urls.py
from django.urls import path
from .views import (
    article_list_view,
    article_detail_view,
    article_search_view,
    article_create_view,
    article_update_view,
    article_delete_view,
)

app_name = 'articles'

urlpatterns = [
    path('', article_list_view, name='article_list'),
    path('detail/<slug:slug>/', article_detail_view, name='article_detail'),
    path('search/', article_search_view, name='article_search'),
    path('create/', article_create_view, name='article_create'),
    path('edit/<int:pk>/', article_update_view, name='article_update'),
    path('delete/<int:pk>/', article_delete_view, name='article_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('recipe/', include('recipes.urls', namespace='recipes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


class ArticleQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is not None:
            lookup = Q(title__icontains=query) | Q(content__icontains=query)
            return self.filter(lookup)
        return self.none()

class SearchManager(models.Manager):

    def get_queryset(self):
        return ArticleQuerySet(self.model)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class Article(models.Model):
    title = models.CharField(max_length=221)
    slug = models.SlugField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)

    objects = SearchManager()

    def __str__(self):
        return self.title

    @property
    def get_absolute_url(self):
        # return f'/{self.slug}/'
        return reverse('articles:article_detail', kwargs={'slug': self.slug})


    # def save(self, *args, **kwargs):
    #     if self.slug is None:
    #         self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)
    #     print('save')


@receiver(pre_save, sender=Article)
def article_pre_save(sender, instance, *args, **kwargs):
    print('pre_save')
    # if instance.slug is None:
    #     instance.slug = slugify(instance.title)


def article_post_save(sender, instance, created, *args, **kwargs):
    print('post_save')
    if created:
        if instance.slug is None:
            instance.slug = slugify(instance.title)
            instance.save()


# pre_save.connect(article_pre_save, sender=Article)
# post_save.connect(article_post_save, sender=Article)

articles/forms.py
from django import forms
from .models import Article


class _ArticleCreateForm(forms.Form):
    title = forms.CharField(max_length=221)
    content = forms.CharField(max_length=221)



class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

articles/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from django.db.models import Q

from .models import Article
from .forms import ArticleCreateForm


def article_list_view(request):
    articles = Article.objects.all()
    context = {
        'object_list': articles
    }
    return render(request, 'articles/list.html', context)


@login_required
def _article_detail_view(request, pk=None):
    article_obj = None
    if pk is not None:
        article_obj = Article.objects.get(id=pk)

    context = {
        'object': article_obj
    }
    return render(request, 'articles/detail.html', context)


@login_required
def article_detail_view(request, slug=None):
    article_obj = None
    if slug is not None:
        try:
            article_obj = Article.objects.get(slug=slug)
        except Article.DoesNotExist:
            raise Http404
        except Article.MultipleObjectsReturned:
            article_obj = Article.objects.filter(slug=slug).first()
        except Exception as e:
            raise e.args

    context = {
        'object': article_obj
    }
    return render(request, 'articles/detail.html', context)


def article_search_view(request):
    # print(request.GET)
    query_dict = request.GET
    query = query_dict.get('q')
    articles = None
    if query:

        articles = Article.objects.search(query)
    context = {
        'object_list': articles
    }
    return render(request, 'articles/search.html', context)


def _article_create_view(request):
    query_dict = request.POST
    # print(query_dict)
    title = query_dict.get('title')
    content = query_dict.get('content')
    context = {}
    if title:
        object = Article.objects.create(title=title, content=content)
        context['object'] = object

    return render(request, 'articles/create.html', context)


def __article_create_view(request):
    form = ArticleCreateForm(request.POST or None)
    context = {
        'form': form
    }
    if form.is_valid():
        title = form.cleaned_data.get('title')
        content = form.cleaned_data.get('content')
        object = Article.objects.create(title=title, content=content)
        context['object'] = object

    return render(request, 'articles/create.html', context)

@login_required
def article_create_view(request):
    form = ArticleCreateForm(request.POST or None)
    context = {
        'form': form
    }
    if form.is_valid():
        object = form.save()
        context['object'] = object

    return render(request, 'articles/create.html', context)


@login_required()
def article_update_view(request, pk=None):
    article_obj = None
    if pk is not None:
        article_obj = Article.objects.get(id=pk)
    form = ArticleCreateForm(instance=article_obj)
    # title = request.POST.get('title')
    # content = request.POST.get('content')
    if request.method == 'POST':
        # article_obj.title = title
        # article_obj.content = content
        # article_obj.save()
        form = ArticleCreateForm(request.POST, instance=article_obj)
        if form.is_valid():
            form.save()
            return redirect('articles:article_detail', article_obj.id)
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)


@login_required()
def article_delete_view(request, pk=None):
    article_obj = None
    if pk is not None:
        article_obj = Article.objects.get(id=pk)
    if request.method == 'POST':
        article_obj.delete()
        return redirect('/')
    context = {
        'object': article_obj
    }
    return render(request, 'articles/delete.html', context)

templates/articles/create.html
{% extends 'base.html' %}


{% block title %}Article create{% endblock %}

{% block content %}
    {% if not object %}
        <form method="post">
            {% csrf_token %}
            {#            <input type="text" name="title">#}
            {#            <input type="text" name="content">#}


            {{ form.as_p }}
            <button type="submit">Add article</button>
        </form>
    {% else %}
        added: <a href="{% url 'articles:article_detail' object.id %}">{{ object.title }}</a>
    {% endif %}
{% endblock %}

templates/articles/delete.html
{% extends 'base.html' %}


{% block title %}Delete article{% endblock %}


{% block content %}
    <h3>{{ object.title }}</h3>
    <p>Rostandan ochirmoqchimisiz</p>
    <form method="post">
        {% csrf_token %}

        <button type="submit">Yes, Delete</button>
        <a href="{% url 'articles:article_list' %}">Yoq, orqaga</a>
    </form>

{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article detail{% endblock %}


{% block content %}

    <h1>{{ object.title }} ({{ object.id }})</h1>
    {% if object.content %}
        <p>{{ object.content }}</p>
    {% endif %}
{% endblock %}

templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Article list{% endblock %}
{% block content %}

    <form action="{% url 'articles:article_search' %}" method="get">
        <input type="search" name="q">
        <input type="submit" value="search">
    </form>

    <div>
        <ul>
            {% for object in object_list %}
                {#     <li><a href="{{ object.id }}/">{{ object }}</a></li>#}
                <li>
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a> |
                    <a href="{% url 'articles:article_update' object.id %}">edit</a> |
                    <a href="{% url 'articles:article_delete' object.id %}">delete</a>
                </li>

            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/articles/search.html
{% extends 'base.html' %}

{% block title %}Article search list{% endblock %}
{% block content %}

    <div>
        <ul>
            {% for object in object_list %}
                {#     <li><a href="{{ object.id }}/">{{ object }}</a></li>#}
                <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>

            {% endfor %}
        </ul>
    </div>
{% endblock %}