accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

articles/urls.py
from django.urls import path
from .views import (
    article_list_view,
    article_detail_view,
    article_search_view,
    article_create_view,
    article_update_view,
    article_delete_view,
)

app_name = 'articles'

urlpatterns = [
    path('', article_list_view, name='article_list'),
    path('detail/<slug:slug>/', article_detail_view, name='article_detail'),
    path('search/', article_search_view, name='article_search'),
    path('create/', article_create_view, name='article_create'),
    path('edit/<int:pk>/', article_update_view, name='article_update'),
    path('delete/<int:pk>/', article_delete_view, name='article_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('recipe/', include('recipes.urls', namespace='recipes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_edit_view,
    recipe_delete_view,
)

app_name = 'recipes'

urlpatterns = [
    path('list/', recipe_list_view, name='list'),
    path('detail/<slug:slug>/', recipe_detail_view, name='detail'),
    path('create/', recipe_create_view, name='create'),
    path('edit/<int:pk>/', recipe_edit_view, name='edit'),
    path('delete/<int:pk>/', recipe_delete_view, name='delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Try django{% endblock %}</title>
</head>
<body>

<header>
    {% include 'navbar.html' %}
</header>

{% block content %}

{% endblock %}

</body>
</html>

templates/navbar.html
<style>
    nav {
        padding: 20px;
        background-color: dimgrey;
        color: aliceblue;
        margin-bottom: 20px;
    }

    .nav-list {
        display: inline-flex;

    }

    .nav-list li {
        display: inline;
        margin-left: 20px;
    }

    .nav-list li a {
        color: aliceblue;
    }
</style>

<nav>
    <ul class="nav-list">
        <li>
            <a href="/">
                home
            </a>
        </li>
        <li>
            <a href="{% url 'articles:article_list' %}">
                articles
            </a>
        </li>
        <li>
            <a href="{% url 'articles:article_create' %}">
                add new article
            </a>
        </li>
        <li>
            <a href="{% url 'recipes:list' %}">
                recipes
            </a>
        </li>
        <li>
            <a href="{% url 'recipes:create' %}">
                add new recipe
            </a>
        </li>
    </ul>
    <ul class="nav-list" style="float: right">
        {% if request.user.is_authenticated %}
            <li>
                {{ request.user }}
            </li>
            <li>
                <a href="{% url 'accounts:logout' %}">Logout</a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'accounts:login' %}">Login</a>
            </li>
        {% endif %}
    </ul>
</nav>