config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('recipe/', include('recipes.urls', namespace='recipes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_edit_view,
    recipe_delete_view,
)

app_name = 'recipes'

urlpatterns = [
    path('list/', recipe_list_view, name='list'),
    path('detail/<slug:slug>/', recipe_detail_view, name='detail'),
    path('create/', recipe_create_view, name='create'),
    path('edit/<int:pk>/', recipe_edit_view, name='edit'),
    path('delete/<int:pk>/', recipe_delete_view, name='delete'),

]

recipes/models.py
from django.db import models
from django.utils.text import slugify

from .validators import validator_of_units
from django.db.models.signals import pre_save, post_save


class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tag(models.Model):
    tag = models.CharField(max_length=21)

    def __str__(self):
        return self.tag

class Recipe(Timestamp):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=221)
    img = models.ImageField(null=True, upload_to='recipe')
    slug = models.SlugField(blank=True, unique=True, null=True)
    tags = models.ManyToManyField(Tag)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    # recipeingrident_set
    # <model_name>_set



class RecipeIngredient(Timestamp):
    UNITS = (
        (0, 'KG'),  # get_<fielld_name>_display
        (1, 'L'),
        (2, 'SHT'),
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient_name = models.CharField(max_length=221, help_text='kamroq soz bilan tarifla')
    quantity = models.FloatField()
    # unit = models.CharField(max_length=21, validators=[validator_of_units])  # kg, l, sht
    unit = models.IntegerField(choices=UNITS, default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.ingredient_name



def recipe_post_save(sender, instance, created, *args, **kwargs):
    if created:
        instance.slug = slugify(f"{instance.user_id} {instance.name}")
        instance.save()



post_save.connect(recipe_post_save, sender=Recipe)

recipes/forms.py
from django import forms
from .models import Recipe, RecipeIngredient


class RecipesForm(forms.ModelForm):
    class Meta:
        model = Recipe
        exclude = ['slug', 'user', 'is_active']


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = '__all__'
        exclude = ['recipe']

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Recipe, RecipeIngredient
from .forms import RecipesForm, RecipeIngredientForm
from django.forms import modelformset_factory


def recipe_list_view(request):
    recipes = Recipe.objects.all()

    context = {
        'object_list': recipes
    }

    return render(request, 'recipes/list.html', context)


def recipe_detail_view(request, slug=None):
    obj = None
    if slug is not None:
        obj = Recipe.objects.get(slug=slug)


    context = {
        'object': obj
    }

    return render(request, 'recipes/detail.html', context)


@login_required
def recipe_create_view(request):
    form = RecipesForm(request.POST or None, request.FILES or None)
    FormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=1)
    qs = RecipeIngredient.objects.none()
    formset = FormSet(request.POST or None, queryset=qs)
    if form.is_valid() and formset.is_valid():
        obj = form.save(commit=False)
        obj.user_id = request.user.id
        obj.save()
        form.save_m2m()

        for form in formset:
            obj2 = form.save(commit=False)
            if form.cleaned_data.get('ingredient_name') and form.cleaned_data.get('quantity'):
                obj2.recipe_id = obj.id
                obj2.save()

        return redirect('recipes:detail', obj.slug)

    context = {
        'form': form,
        'formset': formset,
    }

    return render(request, 'recipes/create.html', context)


def recipe_edit_view(request, pk=None):
    obj = None
    context = {

    }
    if pk is not None:
        obj = Recipe.objects.get(id=pk)
        form = RecipesForm(request.POST or None, request.FILES or None, instance=obj)
        FormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=1)
        qs = RecipeIngredient.objects.filter(recipe_id=pk)
        formset = FormSet(request.POST or None, queryset=qs)
        context['form'] = form
        context['formset'] = formset
        if form.is_valid() and formset.is_valid():
            obj = form.save(commit=False)
            obj.save()
            form.save_m2m()

            for form in formset:
                obj2 = form.save(commit=False)
                if form.cleaned_data.get('ingredient_name') and form.cleaned_data.get('quantity'):
                    obj2.recipe_id = obj.id
                    obj2.save()

            return redirect('recipes:detail', obj.slug)

    return render(request, 'recipes/edit.html', context)


def recipe_delete_view(request, pk=None):

    obj = None
    if pk is not None:
        obj = Recipe.objects.get(id=pk)
        if request.method == 'POST':

            obj.delete()
            return redirect('recipes:list')

    context = {
        'object': obj
    }

    return render(request, 'recipes/delete.html', context)

templates/recipes/create.html
{% extends 'base.html' %}

{% block title %}Recipes create{% endblock %}


{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.as_p }}
        <button type="submit">add</button>
    </form>



{% endblock %}

templates/recipes/delete.html
{% extends 'base.html' %}

{% block title %}Recipes delete{% endblock %}


{% block content %}

    <form method="post">
    {% csrf_token %}
        <h1>{{ object.name }}</h1>
    <p style="color: red">Rostan ochirvormoqchimsiz </p>
    <div>
            <button type="submit" style="color: white;background-color: red">Delete</button>
            <a href="{% url 'recipes:detail' object.slug %}" style="color: dodgerblue">cancel</a>
        </div>
    </form>

{% endblock %}

templates/recipes/detail.html
{% extends 'base.html' %}

{% block title %}Recipes detail{% endblock %}


{% block content %}

    <h2>{{ object.name }}</h2>
    {% if object.img %}
    <img src="{{ object.img.url }}" alt="">
    {% endif %}

    <p>author: {{ object.user }}</p>
    <p>
        tags: {% for tag in object.tags.all %}#{{ tag }} {% endfor %}
    </p>
    <hr>

    {% if object.recipeingredient_set.all %}
        <h3>Ingredients</h3>
        <ol>
            {% for inredient in object.recipeingredient_set.all %}
                <li>{{ inredient.ingredient_name }} -> {{ inredient.quantity }} {{ inredient.get_unit_display.lower }}</li>
            {% endfor %}

        </ol>
    {% else %}
        <p style="color: darkred">this recipe has no ingredient</p>
    {% endif %}


    {% if request.user.id == object.user_id %}
        <hr>
        <div>
            <a href="{% url 'recipes:edit' object.id %}" style="color: dodgerblue">Edit</a>
            <a href="{% url 'recipes:delete' object.id %}" style="color: red">Delete</a>
        </div>
    {% endif %}


{% endblock %}

templates/recipes/edit.html
{% extends 'base.html' %}

{% block title %}Recipes edit{% endblock %}


{% block content %}
    <form method="post">
        {{ formset.management_form }}
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.as_p }}
        <button type="submit">add</button>
    </form>

{% endblock %}

templates/recipes/list.html
{% extends 'base.html' %}

{% block title %}Recipes list{% endblock %}


{% block content %}
    
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'recipes:detail' object.slug %}">{{ object.name }}</a> -> {{ object.user }}</li>
        {% endfor %}
        
    </ul>


{% endblock %}